import { Currency, RecurrenceFrequency } from './types';

export const DEFAULT_CATEGORIES: string[] = [
  'Food',
  'Transport',
  'Bills',
  'Entertainment',
  'Shopping',
  'Groceries',
  'Salary',
  'Investments',
  'Healthcare',
  'Education',
  'Housing',
  'Utilities',
  'Travel',
  'Personal Care',
  'Gifts',
  'Others',
];

export const GEMINI_MODEL_TEXT = 'gemini-2.5-flash';

export const RECURRENCE_FREQUENCIES: RecurrenceFrequency[] = ['daily', 'weekly', 'monthly', 'yearly'];

export const CURRENCY_OPTIONS: Currency[] = [
  { code: 'USD', name: 'United States Dollar', symbol: '$' },
  { code: 'EUR', name: 'Euro', symbol: '€' },
  { code: 'GBP', name: 'British Pound Sterling', symbol: '£' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$' },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽' },
  { code: 'MXN', name: 'Mexican Peso', symbol: 'Mex$' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R' },
  { code: 'AED', name: 'United Arab Emirates Dirham', symbol: 'د.إ' },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$' },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$' },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr' },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr' },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr.' },
  { code: 'PLN', name: 'Polish Złoty', symbol: 'zł' },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺' },
  { code: 'THB', name: 'Thai Baht', symbol: '฿' },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp' },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM' },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱' },
  { code: 'VND', name: 'Vietnamese Đồng', symbol: '₫' },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£' },
  { code: 'CLP', name: 'Chilean Peso', symbol: '$' },
  { code: 'COP', name: 'Colombian Peso', symbol: '$' },
  { code: 'ARS', name: 'Argentine Peso', symbol: '$' },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨' },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳' },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨' },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: '₨' },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴' },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦' },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh' },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh' },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh' },
  { code: 'XAF', name: 'CFA Franc BEAC', symbol: 'FCFA' },
  { code: 'XOF', name: 'CFA Franc BCEAO', symbol: 'CFA' },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.' },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج' },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت' },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د' },
  { code: 'QAR', name: 'Qatari Riyal', symbol: '﷼' },
  { code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك' },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب' },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا' },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل' },
  { code: 'SYP', name: 'Syrian Pound', symbol: 'ل.س' },
  { code: 'YER', name: 'Yemeni Rial', symbol: '﷼' },
  { code: 'AFN', name: 'Afghan Afghani', symbol: '؋' },
  { code: 'ALL', name: 'Albanian Lek', symbol: 'L' },
  { code: 'AMD', name: 'Armenian Dram', symbol: '֏' },
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz' },
  { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ' },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼' },
  { code: 'BAM', name: 'Bosnia and Herzegovina Convertible Mark', symbol: 'KM' },
  { code: 'BBD', name: 'Barbadian Dollar', symbol: '$' },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв' },
  { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu' },
  { code: 'BMD', name: 'Bermudian Dollar', symbol: '$' },
  { code: 'BND', name: 'Brunei Dollar', symbol: '$' },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs.' },
  { code: 'BSD', name: 'Bahamian Dollar', symbol: '$' },
  { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.' },
  { code: 'BWP', name: 'Botswana Pula', symbol: 'P' },
  { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br' },
  { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$' },
  { code: 'CDF', name: 'Congolese Franc', symbol: 'FC' },
  { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡' },
  { code: 'CUP', name: 'Cuban Peso', symbol: '$' },
  { code: 'CVE', name: 'Cape Verdean Escudo', symbol: 'Esc' },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč' },
  { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj' },
  { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$' },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br' },
  { code: 'FJD', name: 'Fijian Dollar', symbol: 'FJ$' },
  { code: 'FKP', name: 'Falkland Islands Pound', symbol: '£' },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾' },
  { code: 'GGP', name: 'Guernsey Pound', symbol: '£' },
  { code: 'GIP', name: 'Gibraltar Pound', symbol: '£' },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D' },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'FG' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q' },
  { code: 'GYD', name: 'Guyanese Dollar', symbol: '$' },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'L' },
  { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn' },
  { code: 'HTG', name: 'Haitian Gourde', symbol: 'G' },
  { code: 'IMP', name: 'Isle of Man Pound', symbol: '£' },
  { code: 'IRR', name: 'Iranian Rial', symbol: '﷼' },
  { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr' },
  { code: 'JEP', name: 'Jersey Pound', symbol: '£' },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$' },
  { code: 'KGS', name: 'Kyrgyzstani Som', symbol: 'с' },
  { code: 'KHR', name: 'Cambodian Riel', symbol: '៛' },
  { code: 'KMF', name: 'Comorian Franc', symbol: 'CF' },
  { code: 'KPW', name: 'North Korean Won', symbol: '₩' },
  { code: 'KYD', name: 'Cayman Islands Dollar', symbol: '$' },
  { code: 'LAK', name: 'Lao Kip', symbol: '₭' },
  { code: 'LRD', name: 'Liberian Dollar', symbol: '$' },
  { code: 'LSL', name: 'Lesotho Loti', symbol: 'L' },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د' },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'L' },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar' },
  { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден' },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'Ks' },
  { code: 'MNT', name: 'Mongolian Tögrög', symbol: '₮' },
  { code: 'MOP', name: 'Macanese Pataca', symbol: 'P' },
  { code: 'MRO', name: 'Mauritanian Ouguiya (pre-2018)', symbol: 'UM' }, // Deprecated
  { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM' },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨' },
  { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf' },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK' },
  { code: 'NAD', name: 'Namibian Dollar', symbol: '$' },
  { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$' },
  { code: 'Nok', name: 'Norwegian Krone', symbol: 'kr' }, // Duplicate, use NOK
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K' },
  { code: 'PYG', name: 'Paraguayan Guaraní', symbol: '₲' },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei' },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'дин.' },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'Fr' },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: '$' },
  { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨' },
  { code: 'SDG', name: 'Sudanese Pound', symbol: '£' },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'Sh' },
  { code: 'SRD', name: 'Surinamese Dollar', symbol: '$' },
  { code: 'SSP', name: 'South Sudanese Pound', symbol: '£' },
  { code: 'STD', name: 'São Tomé and Príncipe Dobra (pre-2018)', symbol: 'Db' }, // Deprecated
  { code: 'STN', name: 'São Tomé and Príncipe Dobra', symbol: 'Db' },
  { code: 'SVC', name: 'Salvadoran Colón', symbol: '₡' },
  { code: 'SZL', name: 'Eswatini Lilangeni', symbol: 'L' },
  { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'ЅМ' },
  { code: 'TMT', name: 'Turkmenistan Manat', symbol: 'm' },
  { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$' },
  { code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: 'TT$' },
  { code: 'TVD', name: 'Tuvaluan Dollar', symbol: '$' },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U' },
  { code: 'UZS', name: 'Uzbekistani Som', symbol: 'лв' },
  { code: 'VES', name: 'Venezuelan Bolívar Soberano', symbol: 'Bs.S' },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'Vt' },
  { code: 'WST', name: 'Samoan Tala', symbol: 'WS$' },
  { code: 'XCD', name: 'East Caribbean Dollar', symbol: '$' },
  { code: 'XPF', name: 'CFP Franc', symbol: '₣' },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK' },
  { code: 'ZWL', name: 'Zimbabwean Dollar', symbol: 'Z$' },
];

export const DEFAULT_CURRENCY_CODE = 'USD';

// Hardcoded exchange rates for demonstration purposes.
// In a real application, these would come from a secure, real-time API.
// Rates are relative to USD (USD: 1)
export const hardcodedExchangeRates: { [key: string]: number } = {
  USD: 1.0,
  EUR: 0.93,
  GBP: 0.79,
  JPY: 156.90,
  CAD: 1.37,
  AUD: 1.51,
  CHF: 0.91,
  CNY: 7.25,
  INR: 83.47,
  BRL: 5.14,
  RUB: 91.50,
  MXN: 16.73,
  ZAR: 18.25,
  AED: 3.67,
  SAR: 3.75,
  SGD: 1.35,
  HKD: 7.82,
  NZD: 1.63,
  KRW: 1370.0,
  SEK: 10.87,
  NOK: 10.88,
  DKK: 6.94,
  PLN: 3.98,
  TRY: 32.22,
  THB: 36.70,
  IDR: 16220.0,
  MYR: 4.71,
  PHP: 58.0,
  VND: 25420.0,
  EGP: 47.70,
  CLP: 935.0,
  COP: 3880.0,
  ARS: 880.0,
  PKR: 278.0,
  BDT: 109.5,
  NPR: 130.0,
  LKR: 300.0,
  KZT: 445.0,
  UAH: 39.5,
  GHS: 14.0,
  NGN: 1470.0,
  KES: 130.0,
  TZS: 2570.0,
  UGX: 3780.0,
  XAF: 610.0, // CFA Franc BEAC (approx against USD via EUR)
  XOF: 610.0, // CFA Franc BCEAO (approx against USD via EUR)
  MAD: 10.0,
  DZD: 134.0,
  TND: 3.14,
  IQD: 1310.0,
  QAR: 3.64,
  OMR: 0.385,
  KWD: 0.307,
  BHD: 0.377,
  JOD: 0.709,
  LBP: 89000.0, // Highly variable
  SYP: 13500.0, // Highly variable
  YER: 250.0, // Highly variable
  AFN: 71.0,
  ALL: 93.0,
  AMD: 387.0,
  AOA: 850.0,
  AWG: 1.8,
  AZN: 1.7,
  BAM: 1.82,
  BBD: 2.0,
  BGN: 1.82,
  BIF: 2800.0,
  BMD: 1.0,
  BND: 1.35,
  BOB: 6.9,
  BSD: 1.0,
  BTN: 83.0,
  BWP: 13.6,
  BYN: 3.25,
  BZD: 2.0,
  CDF: 2780.0,
  CRC: 515.0,
  CUP: 24.0,
  CVE: 102.0,
  CZK: 23.0,
  DJF: 178.0,
  DOP: 58.5,
  ETB: 57.0,
  FJD: 2.25,
  FKP: 0.79,
  GEL: 2.7,
  GGP: 0.79,
  GIP: 0.79,
  GMD: 67.0,
  GNF: 8600.0,
  GTQ: 7.75,
  GYD: 208.0,
  HNL: 24.5,
  HRK: 7.0, // Croatian Kuna, replaced by EUR
  HTG: 132.0,
  IMP: 0.79,
  IRR: 42000.0,
  ISK: 138.0,
  JEP: 0.79,
  JMD: 155.0,
  KGS: 89.0,
  KHR: 4080.0,
  KMF: 460.0,
  KPW: 900.0, // North Korean Won, highly restricted
  KYD: 0.83,
  LAK: 20000.0,
  LRD: 190.0,
  LSL: 18.25,
  LYD: 4.85,
  MDL: 17.8,
  MGA: 4500.0,
  MKD: 57.0,
  MMK: 2100.0,
  MNT: 3450.0,
  MOP: 8.0,
  MRO: 357.0, // Deprecated, using MRU below
  MRU: 35.7,
  MUR: 46.0,
  MVR: 15.3,
  MWK: 1700.0,
  NAD: 18.25,
  NIO: 36.6,
  PGK: 3.8,
  PYG: 7500.0,
  RON: 4.6,
  RSD: 109.0,
  RWF: 1300.0,
  SBD: 8.4,
  SCR: 13.5,
  SDG: 600.0, // Highly variable
  SOS: 570.0,
  SRD: 33.0,
  SSP: 1300.0, // Highly variable
  STD: 22000.0, // Deprecated, using STN below
  STN: 22.0,
  SVC: 8.75,
  SZL: 18.25,
  TJS: 10.9,
  TMT: 3.5,
  TOP: 2.3,
  TTD: 6.78,
  TVD: 1.51, // Tuvaluan Dollar, typically AUD
  UYU: 39.0,
  UZS: 12600.0,
  VES: 36.0, // Venezuelan Bolívar Soberano, highly variable
  VUV: 119.0,
  WST: 2.7,
  XPF: 110.0, // CFP Franc (approx against USD via EUR)
  ZMW: 26.0,
  ZWL: 30000.0, // Zimbabwean Dollar, highly variable
};